---
title: "Fiddler crab sizes"
format: html
editor: visual
execute: 
  echo: false
  warning: false
---

## Fiddle Crabs

We looked at Fiddle crab carapace sizes based on the latitudes of different observation sites. The main takeaway is that crab sizes generally increased with latitude.

```{r}
library(lterdatasampler)
library(tidyverse)
library(kableExtra)
```

```{r}
View(pie_crab)
```

### I am creating a plot of fiddler crab carapace widths observed at the different latitudes

```{r}
ggplot(pie_crab, aes(x = latitude
                     , y = size)) +
  geom_jitter(aes(color = latitude)) + 
  theme_minimal() + 
  labs(title = "Fiddler Crab Carapace in different Latitudes", 
       y = "Carapace width", 
       x = "Latitude", 
       caption = "This is our caption! Conga Crabs!!!") 
```

### Summary Table

```{r}
crab_summary <- pie_crab |> 
  group_by(site) |>
  summarize(mean = round(mean(size, na.rm = TRUE), 2)
            , standard_deviation = round(sd(size, na.rm = TRUE), 2) 
            , sample_size = n())
```

```{r}
crab_summary %>% 
  kable(col.names = c("Site", "Size Mean (mm)", "Size Standard Deviation (mm)", "Sample Size")) %>% 
  kable_styling(bootstrap_options = "striped") %>% 
  column_spec(1, bold = TRUE, background = "orange") %>% 
  add_header_above(c(" " = 2, "Crab sizes by site" = 2)) 
```
